# Generated by Django 5.2.4 on 2025-08-04 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '__first__'),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitReason', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
                ('visit_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('is_follow_u_required', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_date', models.DateField()),
                ('scheduledTime', models.TimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming')])),
                ('notes', models.TextField(max_length=500)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicineName', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('instructions', models.TextField(max_length=500)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultation.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testType', models.CharField(max_length=200)),
                ('resultSummary', models.TextField(max_length=500)),
                ('reportFileUrl', models.FileField(upload_to='reports/')),
                ('testDate', models.DateField()),
                ('testTime', models.TimeField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='consultation.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
