# Generated by Django 5.2.4 on 2025-08-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
    ]
