# Generated by Django 5.2.4 on 2025-08-07 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('license_number', models.CharField(max_length=50)),
                ('year_of_experience', models.PositiveIntegerField()),
                ('hospital_name', models.CharField(max_length=200)),
                ('available_timings', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctor',
            },
        ),
    ]
